### ISSUE TITLE
Multi-User setup

### ISSUE THREAD

**Issue by maufl** [BodnarSoft/KeePass-Smart-Certificate-Key-Provider#2]
Hey, I'm currently using this plugin for myself and it works well, thanks! I was wondering whether I could encrypt a KeePass database for multiple keys? So that I could share a database with colleagues and they could all encrypt/decrypt it with their own smart card?

**Comment by FrantisekBodnar** [comment]
Hi Felix, I'm glad that you are using my plugin :) 

Unfortunately, what do you want is not possible. It is like that you would use several different passwords on one KeePass DB. 

The password and the information from Smart Card is used to encrypt the DB (_like two passwords, one that you type in Master Password field and second one is generated from SmartCard_).

Only way is to use shared RSA certificate and Master Password to access the KeePass DB. 

Look on this article [General Information about Shared Databases](https://keepass.info/help/base/multiuser.html).

If you want to use Shared records from a database, you have to use another software like [LastPass](https://www.lastpass.com), that allows to share secured records.

Best
Franky

**Comment by maufl** [comment]
Oh OK. I expected the public/private key pair on the smart card to be used to encrypt the master password. Then it should be possible to encrypt the master password for multiple public keys, kind of like encrypting a file with GPG for multiple recipients. I'm not sure I understand why this is not possible with KeePass but I guess it's due to the way it uses encryption.
