### ISSUE TITLE
Remember certificate choice between launches

### ISSUE THREAD

**Issue by DidierA** [BodnarSoft/KeePass-Smart-Certificate-Key-Provider#3]
Thank you for this plugin, it does a great job allowing me to only remember my smart card's PIN and not another long passphrase ;)
I have multiple cettificates available on the smartcard and in windows' store; when I choose the right one at the prompt everything goes well, I can unlock the database and use it; and if I lock it I can unlock it later without choosing the cert again.
However If I close the application, I need to select the correct certificate again at launch. It would be nice if the associated certificate was remembered also between launches.

**Comment by FrantisekBodnar** [comment]
Hi sorry for really late response. :)

Yes that is true, it remembers the valid certificate only in memory of running application. I did it for security reasons, so this information is available in protected memory so it can't be accessed by some virus or malware.

Also I strongly suggest that you also use the Master Password with the certificate for security reasons, to maximize security in case your certificate were stolen from your backup storage.

Best
Franky
