### ISSUE TITLE
One database, multiple smart cards?

### ISSUE THREAD

**Issue by ltojth** [BodnarSoft/KeePass-Smart-Certificate-Key-Provider#6]
Is it possible to allow multiple smart cards to unlock the database? I'm trying to set this up at work where we have multiple people that access one database, but I can only seem to add just the one smart card.

(Also, just as a side note, this plugin is working perfectly with NHS Identity Service smart cards.)

**Comment by FrantisekBodnar** [comment]
Sorry for super late response, but unfortunately the **answer is NO**!

KeePass was not designed as multi user application, where different users with different credentials (_like passwords or Key Providers_) can access (_save and open_) same the KeePass database. 
The plugin is like "addition" to the master password, just in hidden form, that is generated by the certificate of the Smart Card. 

If you are looking for Multi User password manager, it can't be KeePass, unless the KeePass developer will change it to support such feature.
