### ISSUE TITLE
Yubikey reset

### ISSUE THREAD

**Issue by TonyStark02** [BodnarSoft/KeePass-Smart-Certificate-Key-Provider#9]
Hello,

I locked my yubi so i had to reset it.

I exported the cert before that.

After the reset, I reimported the cert but it's impossible to open my database anymore...
Because of a private key problem?

Is there any way to open my database by overriding the key auth?

**Comment by FrantisekBodnar** [comment]
Hello, 
you need to have same private key, so if you had **PFX** cert file (_that contains also the private key with all cert details_) in some secure backup it should work. 
I did that several times in same scenario as you are facing now or I got new USB Smart card device and it works without any issues. I just took it from backup and imported it to the Smart card and it works, even on multiple different devices. 

FYI: I have self-signed certificate.

**Comment by FrantisekBodnar** [comment]
> Is there any way to open my database by overriding the key auth?

It can be "overridden" and send to unlock KeePass by modifying the code of the plugin (_not possible by default_), but you would need to know what the exact hash (_like secrete password_), that was generated by private key of your certificate in the plugin. 
So this is long answer, to your question 😄 The short one is NO 😉

**Comment by TonyStark02** [comment]
Hello, 

Thank you for your answers :)
